MPY_TOOL_LONGINT_IMPL ?= -mlongint-impl=mpz
LONGINT_IMPL ?= MPZ
INTERNAL_LIBM ?= 1
USB_SERIAL_NUMBER_LENGTH ?= 24

ifeq ($(MCU_VARIANT),STM32F405xx)
	CIRCUITPY_FRAMEBUFFERIO ?= 1
	CIRCUITPY_RGBMATRIX ?= 1
	CIRCUITPY_SDIOIO ?= 1
	USB_NUM_EP = 4
endif

ifeq ($(MCU_SERIES),F1)
	# Not yet implemented common-hal modules:
	CIRCUITPY_MICROCONTROLLER = 0 # Typically the first module to create
	CIRCUITPY_DIGITALIO = 0       # Typically the second module to create
	CIRCUITPY_ANALOGIO = 0
	CIRCUITPY_BUSIO = 0
	CIRCUITPY_NEOPIXEL_WRITE = 0
	CIRCUITPY_PULSEIO = 0
	CIRCUITPY_OS = 0
	CIRCUITPY_NVM = 0
	CIRCUITPY_AUDIOBUSIO = 0
	CIRCUITPY_AUDIOIO = 0
	CIRCUITPY_COUNTIO ?= 0
	CIRCUITPY_ROTARYIO = 0
	CIRCUITPY_RTC = 0
	CIRCUITPY_FREQUENCYIO = 0
	CIRCUITPY_I2CPERIPHERAL = 0
	CIRCUITPY_DISPLAYIO = 0       # Requires SPI, PulseIO (stub ok)

	# These modules are implemented in shared-module/ - they can be included in
	# any port once their prerequisites in common-hal are complete.
	CIRCUITPY_BITBANGIO = 0       # Requires DigitalIO
	CIRCUITPY_GAMEPAD = 0         # Requires DigitalIO
	CIRCUITPY_PIXELBUF = 0        # Requires neopixel_write or SPI (dotstar)
	CIRCUITPY_RANDOM = 0          # Requires OS
	CIRCUITPY_STORAGE = 0         # Requires OS, filesystem
	CIRCUITPY_TOUCHIO = 0         # Requires Microcontroller
	CIRCUITPY_USB_HID = 0         # Requires USB
	CIRCUITPY_USB_MIDI = 0        # Requires USB
	CIRCUITPY_REQUIRE_I2C_PULLUPS = 0 # Does nothing without I2C
	CIRCUITPY_ULAB = 0            # No requirements, but takes extra flash
endif

ifeq ($(MCU_SERIES),F4)
	# Not yet implemented common-hal modules:
	CIRCUITPY_AUDIOBUSIO ?= 0
	CIRCUITPY_AUDIOIO ?= 0
	CIRCUITPY_COUNTIO ?= 0
	CIRCUITPY_FREQUENCYIO ?= 0
	CIRCUITPY_I2CPERIPHERAL ?= 0
	CIRCUITPY_NVM ?= 0
	CIRCUITPY_ROTARYIO ?= 0
	CIRCUITPY_RTC ?= 0
	CIRCUITPY_USB_MIDI ?= 0
	CIRCUITPY_USB_HID ?= 0
endif

ifeq ($(MCU_SERIES),H7)
	# Not yet implemented common-hal modules:
	CIRCUITPY_ANALOGIO ?= 0
	CIRCUITPY_AUDIOBUSIO ?= 0
	CIRCUITPY_AUDIOIO ?= 0
	CIRCUITPY_COUNTIO ?= 0
	CIRCUITPY_FREQUENCYIO ?= 0
	CIRCUITPY_I2CPERIPHERAL ?= 0
	CIRCUITPY_NEOPIXEL_WRITE ?= 0
	CIRCUITPY_NVM ?= 0
	CIRCUITPY_PULSEIO ?= 0
	CIRCUITPY_ROTARYIO ?= 0
	CIRCUITPY_RTC ?= 0
	CIRCUITPY_USB_HID ?= 0
	CIRCUITPY_USB_MIDI ?= 0
endif

ifeq ($(MCU_SERIES),F7)
	# Not yet implemented common-hal modules:
	CIRCUITPY_ANALOGIO ?= 0
	CIRCUITPY_AUDIOBUSIO ?= 0
	CIRCUITPY_AUDIOIO ?= 0
	CIRCUITPY_COUNTIO ?= 0
	CIRCUITPY_FREQUENCYIO ?= 0
	CIRCUITPY_I2CPERIPHERAL ?= 0
	CIRCUITPY_NEOPIXEL_WRITE ?= 0
	CIRCUITPY_NVM ?= 0
	CIRCUITPY_ROTARYIO ?= 0
	CIRCUITPY_RTC ?= 0
	CIRCUITPY_USB_HID ?= 0
	CIRCUITPY_USB_MIDI ?= 0
endif
