USB_VID = 0x16D0
USB_PID = 0x08C6
USB_PRODUCT = "Keybow 2040"
USB_MANUFACTURER = "Pimoroni"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY__EVE = 1

CIRCUITPY_REQUIRE_I2C_PULLUPS ?= 0
CIRCUITPY_BUSIO_I2C_INTERNAL_PULLUPS ?= 1
